language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0

bundler_args: --without debuga autotest autotest_inotify autotest_tmux autotest_fsevents autotest_growl

gemfile:
  - Gemfile

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenbabel-dev

branches:
  only:
    - master
    - develop
    - /^feature\//

env:
  - TEST_NIST=y
