language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

bundler_args: --without debug profile

gemfile:
  - Gemfile

before_install:
  - sudo add-apt-repository -y ppa:ktns-87/ppa-libint2
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenbabel-dev libint2 libint-dev

before_script:
  - bundle exec rake clean

branches:
  only:
    - master
    - develop
    - /^feature\//

env:
  - TEST_NIST=y

cache:
  - apt
  - bundle
