# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruphy"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Katsuhiko Nishimra"]
  s.date = "2012-03-11"
  s.description = "TODO: longer description of your gem"
  s.email = "ktns.87@gmail.com"
  s.extensions = ["ext/ruphy_gsl/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    "COPYING",
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/.gitignore",
    "ext/ruphy_gsl/cubature.c",
    "ext/ruphy_gsl/cubature.h",
    "ext/ruphy_gsl/extconf.rb",
    "ext/ruphy_gsl/gsl_dummy_func.c",
    "ext/ruphy_gsl/gsl_dummy_func.h",
    "ext/ruphy_gsl/ruphy_gsl.c",
    "ext/ruphy_gsl/ruphy_gsl.h",
    "ext/ruphy_gsl/spop.c",
    "ext/ruphy_gsl/spop.h",
    "ext/ruphy_gsl/spop_combination.c",
    "ext/ruphy_gsl/spop_deriv.c",
    "ext/ruphy_gsl/spop_laplacian.c",
    "ext/ruphy_gsl/spop_multiplier.c",
    "ext/ruphy_gsl/spop_translation.c",
    "ext/ruphy_gsl/spwf.c",
    "ext/ruphy_gsl/spwf.h",
    "ext/ruphy_gsl/spwf_combination.c",
    "ext/ruphy_gsl/spwf_hydrogenic.c",
    "ext/ruphy_gsl/spwf_integrate.c",
    "ext/ruphy_gsl/spwf_integrate.h",
    "ext/ruphy_gsl/spwf_operated.c",
    "ext/ruphy_gsl/utilities.c",
    "lib/ruphy.rb",
    "lib/ruphy/digestable.rb",
    "lib/ruphy/gsl/error.rb",
    "lib/ruphy/gsl/spop.rb",
    "lib/ruphy/gsl/spop/combination.rb",
    "lib/ruphy/gsl/spop/hamiltonian.rb",
    "lib/ruphy/gsl/spop/hamiltonian/hydrogenic.rb",
    "lib/ruphy/gsl/spop/multiplier.rb",
    "lib/ruphy/gsl/spop/translation.rb",
    "lib/ruphy/gsl/spwf.rb",
    "lib/ruphy/gsl/spwf/combination.rb",
    "lib/ruphy/gsl/spwf/hydrogenic.rb",
    "lib/ruphy/gsl/spwf/operated.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "spec/ruphy/gsl/spop/combination_spec.rb",
    "spec/ruphy/gsl/spop/hamiltonian/hydrogenic_spec.rb",
    "spec/ruphy/gsl/spop/multiplier_spec.rb",
    "spec/ruphy/gsl/spop/translation_spec.rb",
    "spec/ruphy/gsl/spop_spec.rb",
    "spec/ruphy/gsl/spwf/combination_spec.rb",
    "spec/ruphy/gsl/spwf/hydrogenic_spec.rb",
    "spec/ruphy/gsl/spwf/operated_spec.rb",
    "spec/ruphy/gsl/spwf_spec.rb",
    "spec/ruphy_gsl_extn_spec.rb",
    "spec/ruphy_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ktns/ruphy"
  s.licenses = ["GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.21"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rake-compiler>, ["~> 0.8.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.21"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rake-compiler>, ["~> 0.8.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.21"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rake-compiler>, ["~> 0.8.0"])
  end
end

