require File.dirname(__FILE__) + '/../../../spec_helper.rb'

describe RuPHY::GSL::SPWF::Operated do
	before do
		@op       = RuPHY::GSL::SPOP::Multiplier.new(1)
		@wf       = RuPHY::GSL::SPWF::Hydrogenic.new(1,0,0,1);
		@operated = described_class.new(@op, @wf)
	end

	subject {@operated}

	shared_examples_for RuPHY::GSL::SPWF::Operated do
		it 'should have proper instance variables' do
			class << subject
				@spwf.should == @wf
				@spop.should == @op
			end
		end

		describe '#to_s' do
			subject {@operated.to_s}

			it {should_not =~ /nil/}
		end
	end
	it_behaves_like RuPHY::GSL::SPWF::Operated

	context 'generated by @op * @wf' do
		before do
			@operated = @op * @wf
		end

		it_behaves_like RuPHY::GSL::SPWF::Operated
	end
end
